### ISSUE TITLE
Support for DTOs

### ISSUE THREAD

**Issue by shaharyr** [pvginkel/NHibernate.OData#19]
I'm trying to create a WebAPI controller that can take and return DTOs and make it support OData. 

The problem is that I'm separating the entities that are mapped to NHibernate and the DTOs. I need a way to apply OData queries based on DTOs (not on the NHibernate data models).

Looking at the code, it seems that if you can add the ability to call a user method (that will project the member name from one representation to another) inside Parser.ParseMember, it will do the job..

Thanks

**Comment by pvginkel** [comment]
I'm not sure if I follow. Do you need to map the field names as they come in from the query string (the parameters to the `ODataQuery` method)?

**Comment by shaharyr** [comment]
I will try to explain by example.
I have class DtoA which is public to the users and class DataModelA which is private and is mapped to NHibernate. 
Lets say that one of the members in DtoA is called FieldA and DataModelA contains a field called DbFieldA. 
The query string will refer to FieldA, but when translating it to the ICriteria, i need this filed to be replaced with DbFieldA (because that is the field that NHibenate knows..)

**Comment by pvginkel** [comment]
Have a look at this change. This change allows you to provide a custom `NameResolver` on the `ODataParserConfiguration`. An example on how to use this can be found in https://github.com/pvginkel/NHibernate.OData/blob/e2e80aea8e8f1a89fabc9ede480c1ca0639cef84/NHibernate.OData.Test/Criterions/NameResolving.cs.

**Comment by shaharyr** [comment]
I will take a look.
Thanks for the quick reply!!

**Comment by shaharyr** [comment]
I took the last version and it is exactly what i needed.
Thanks a lot

**Comment by pvginkel** [comment]
You're welcome.
