### ISSUE TITLE
CaseSensitive parameter not working

### ISSUE THREAD

**Issue by rodrigosendin** [pvginkel/NHibernate.OData#21]
Hi, 

I'm trying to set the ODATA to perform case insensitive queries. But it is not working.
I did this:

var odataConfig = new ODataParserConfiguration {CaseSensitive = false};
var result = Sessao.ODataQuery<T>(queryStringSelect, odataConfig).List<T>();

I`m using a postgres database.
Am I missing something?

Thanks!

**Comment by dsigitov** [comment]
Can you provide the query string you're trying to execute and the exception (preferably with stack trace)?
I've been using case insensitive queries for a while without any issues.

**Comment by rodrigosendin** [comment]
Hi,

The query string is: ?$filter=substringof(%27carlos%27,Nome)&$orderby=Id&$top=35

The generated SQL QUERY is:
SELECT this_.id                  as id6_0_,      
       this_.Nome                as Nome6_0_      
FROM   public.Beneficiario this_
WHERE  this_.Nome like '%Carlos%' / :p0 /
ORDER  BY this_.id asc
limit  35 / :p1 /

There is no exception. The problem is that on the PostgreSQL we expect IILIKE instead of LIKE:

WHERE  this_.Nome ilike '%Carlos%'

Thanks!

**Comment by netrevisanto** [comment]
+1

**Comment by rodrigosendin** [comment]
Thanks!! It's perfect

**Comment by pvginkel** [comment]
Thanks for the suggestion and @dsigitov pull request. I've pushed a new version to NuGet.
