### ISSUE TITLE
Issue with Any in OData $filter clause.

### ISSUE THREAD

**Issue by adamfairstr** [pvginkel/NHibernate.OData#23]
Hi,

Thanks for this great library. I'd love to see it grow.

I've got an issue with a queries such as:

<i>people?$filter=EmploymentsList/any(o: o/Salary eq 2.5)</i>

Where EmploymentsList is a property on People and is defined as:
```
   private readonly ISet<Employment> employmentsList= new HashSet<Employment>();

   public virtual IEnumerable<Employment> EmploymentsList 
   {
      get { return this.employmentsList; }
   }
```
I receive the following error:

<i>"Cannot get collection item type"</i>

Unfortunately, I cannot change the definition of .EmploymentsList and so would like to change nHibernate.odata instead. I can see the issue lies in NHibernate.OData.TypeUtil.TryGetCollectionItemType at this line:
```
   System.Type enumerableType = collectionType.GetInterfaces().FirstOrDefault(x => x.IsGenericType && x.GetGenericTypeDefinition() == typeof(IEnumerable<>));
```
And enumerableType is returned as null.

Unfortunately, my knowledge of reflection isn't brilliant and would need some pointers but would adding a line such as:
```
   if (enumerableType == null) enumerableType = collectionType;
```
be acceptable? If it is, I'll get on and write a unit test and send a pull request.

**Comment by dsigitov** [comment]
Hi!

> but would adding a line such as:
> `  if (enumerableType == null) enumerableType = collectionType;`
>be acceptable? If it is, I'll get on and write a unit test and send a pull request.

I wouldn't recommend doing that. It will totally break the logic of this method.

The problem is that method doesn't handle correctly the case when `collectionType` is `IEnumerable<T>` itself.

Instead, change the method as follows:

```C#
public static System.Type TryGetCollectionItemType(System.Type collectionType)
{
    if (collectionType == null)
        return null;

    System.Type enumerableType;
    if (collectionType.IsGenericType && collectionType.GetGenericTypeDefinition() == typeof(IEnumerable<>))
        enumerableType = collectionType;
    else
        enumerableType = collectionType.GetInterfaces().FirstOrDefault(x => x.IsGenericType && x.GetGenericTypeDefinition() == typeof(IEnumerable<>));
    
    if (enumerableType == null)
        return null;

    return enumerableType.GetGenericArguments().Single();
}
```

It will first check whether the value of `collectionType` is `IEnumerable<T>` itself, then it will check all  interfaces, so this test will pass:
```C#
Assert.AreEqual(typeof(int), OData.TypeUtil.TryGetCollectionItemType(typeof(IEnumerable<int>)));
```

**Comment by pvginkel** [comment]
Sorry for the late reply. I'll push a new version to NuGet in a moment with this fix.
