### ISSUE TITLE
Query is not supported with substringof and 3 or more clauses

### ISSUE THREAD

**Issue by rodrigosendin** [pvginkel/NHibernate.OData#25]
Hi, 

I'm getting a "Query is not supported" exception when I try to make an odata query using substringof and 3 or more clauses. See this sample:

var result = session.ODataQuery<Beneficiario>("$filter=(DataNascimento eq datetime'1981-03-13T00:00:00' and substringof('Saurin',Nome) and substringof('21906522863',Cpf) and Id eq 55800)")                            .List<Beneficiario>();

The exception is:

Query is not supported
   em NHibernate.OData.QueryVisitorBase`1.LogicalExpression(LogicalExpression expression)
   em NHibernate.OData.CriterionVisitor.ComparisonExpression(ComparisonExpression expression)
   em NHibernate.OData.CriterionVisitor.LogicalExpression(LogicalExpression expression)
   em NHibernate.OData.CriterionVisitor.LogicalExpression(LogicalExpression expression)
   em NHibernate.OData.ODataExpression.ProcessFilter(String value)
   em NHibernate.OData.ODataExpression.ProcessQueryStringPart(String key, String value)
   em NHibernate.OData.ODataExpression.ParseQueryString(String queryString)
   em NHibernate.OData.ODataContext.ODataQuery(ISession session, Type persistentClass, String queryString, ODataParserConfiguration configuration)
   em NHibernate.OData.ODataParser.ODataQuery[T](ISession session, String queryString)
   em Ancode.Med.Testes.TesteOData.ConsultaComfiltro() na C:\TFSAncode\Ancode.Med\src\Ancode.Med\Ancode.Med.Testes\TesteOData.cs:linha 76

Thanks

**Comment by MichaelSaurin** [comment]
+1

**Comment by pvginkel** [comment]
Deployed version 1.7.1.0 to NuGet.
