### ISSUE TITLE
"Not Contains" clause not works

### ISSUE THREAD

**Issue by rodrigosendin** [pvginkel/NHibernate.OData#27]
Hello,

I have a case where I need to filter data with a "not contains" clause. Someting like this:
$filter (substringof('outro',Nome) eq false)

But this clause throw a query not supported exception on NHibernate.OData.
Is there another way to do that? Or any plan to support this clause?

Thanks

**Comment by dsigitov** [comment]
Hello. You can use the following query instead: `$filter=not substringof('outro',Nome)`

**Comment by rodrigosendin** [comment]
Thanks! Works just fine!
